#!/usr/bin/env python3
"""Open a file or folder with sublimetext

uses TextMate-like logic for determining which window to use
"""

import json
import os
import subprocess
import sys


def main():
    for path in sys.argv[1:]:
        subprocess.check_call(
            [
                "subl",
                "--command",
                "open_mate %s"
                % json.dumps(
                    {
                        "path": os.path.abspath(path),
                    }
                ),
            ]
        )


if __name__ == "__main__":
    main()
